-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 17:50:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DULCE_AZALEA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DULCE_AZALEA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DULCE_AZALEA` DEFAULT CHARACTER SET utf8 ;
USE `DULCE_AZALEA` ;

-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `rol` INT NOT NULL,
  `address` VARCHAR(255) NULL, 
  `city` VARCHAR(255) NULL,
  `province` VARCHAR(100) NULL,
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Products` (
  `id_products` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(280) NOT NULL,
  `price` INT(6) NOT NULL,
  `id_categories` INT NULL,
  `image` VARCHAR(255) NOT NULL,
 /*  `created_at` TIMESTAMP NULL, */
  PRIMARY KEY (`id_products`),
  INDEX `fk_Productos_Categorias1_idx` (`id_categories` ASC),
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`id_categories`)
    REFERENCES `DULCE_AZALEA`.`Categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`favorite_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`favorite_products` (
  `id_favorite_products` INT NOT NULL AUTO_INCREMENT,
  `users_id_user` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id_favorite_products`),
  INDEX `fk_favorite_products_Users1_idx` (`users_id_user` ASC),
  INDEX `fk_products_idx` (`product_id` ASC),
  CONSTRAINT `fk_favorite_products_Users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `DULCE_AZALEA`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `DULCE_AZALEA`.`Products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Cart` (
  `id_cart` INT NOT NULL AUTO_INCREMENT,
  `users_id_user` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id_cart`),
  INDEX `fk_favorite_products_Users1_idx` (`users_id_user` ASC),
  INDEX `fk_products_id_idx` (`product_id` ASC),
  CONSTRAINT `fk_favorite_products_Users10`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `DULCE_AZALEA`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_id0`
    FOREIGN KEY (`product_id`)
    REFERENCES `DULCE_AZALEA`.`Products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
