-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 17:50:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DULCE_AZALEA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DULCE_AZALEA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DULCE_AZALEA` DEFAULT CHARACTER SET utf8 ;
USE `DULCE_AZALEA` ;

-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`address_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`address_user` (
  `idUser_direccion` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `province` VARCHAR(100) NULL,
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser_direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `rol` INT NOT NULL,
  `create_at` TIMESTAMP NULL,
  `address_user` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_User_User_direccion1_idx` (`address_user` ASC),
  CONSTRAINT `address_user`
    FOREIGN KEY (`address_user`)
    REFERENCES `DULCE_AZALEA`.`address_user` (`idUser_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Categories` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(280) NOT NULL,
  `price` INT(6) NOT NULL,
  `Categorias_idCategorias` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Productos_Categorias1_idx` (`Categorias_idCategorias` ASC),
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `DULCE_AZALEA`.`Categories` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`favorite_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`favorite_products` (
  `idfavorite_products` INT NOT NULL AUTO_INCREMENT,
  `Users_id_user` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`idfavorite_products`),
  INDEX `fk_favorite_products_Users1_idx` (`Users_id_user` ASC),
  INDEX `fk_produts_idx` (`product_id` ASC),
  CONSTRAINT `fk_favorite_products_Users1`
    FOREIGN KEY (`Users_id_user`)
    REFERENCES `DULCE_AZALEA`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produts`
    FOREIGN KEY (`product_id`)
    REFERENCES `DULCE_AZALEA`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DULCE_AZALEA`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DULCE_AZALEA`.`Cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `Users_id_user` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `fk_favorite_products_Users1_idx` (`Users_id_user` ASC),
  INDEX `fk_products_id_idx` (`product_id` ASC),
  CONSTRAINT `fk_favorite_products_Users10`
    FOREIGN KEY (`Users_id_user`)
    REFERENCES `DULCE_AZALEA`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_id0`
    FOREIGN KEY (`product_id`)
    REFERENCES `DULCE_AZALEA`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
